theme = "monokai_pro_spectrum"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
auto-save = true
auto-format = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "version-control", "spinner", "file-name"]
center = []
right = ["diagnostics", "register", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
ignore = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-messages = true
